# Secret for NexusTradeAI API Keys and Sensitive Data
apiVersion: v1
kind: Secret
metadata:
  name: nexustrade-secrets
  namespace: nexustrade
  labels:
    app: nexustrade-ai
    component: secrets
type: Opaque
data:
  # API Keys (base64 encoded - replace with actual keys in production)
  # These are placeholder values - replace with actual base64-encoded API keys
  ALPHA_VANTAGE_API_KEY: "cGxhY2Vob2xkZXItYWxwaGEtdmFudGFnZS1rZXk="  # placeholder-alpha-vantage-key
  POLYGON_API_KEY: "cGxhY2Vob2xkZXItcG9seWdvbi1rZXk="                     # placeholder-polygon-key
  BYBIT_API_KEY: "cGxhY2Vob2xkZXItYnliaXQta2V5"                           # placeholder-bybit-key
  BYBIT_API_SECRET: "cGxhY2Vob2xkZXItYnliaXQtc2VjcmV0"                   # placeholder-bybit-secret
  
  # Redis Authentication (if required)
  REDIS_PASSWORD: "cGxhY2Vob2xkZXItcmVkaXMtcGFzc3dvcmQ="                  # placeholder-redis-password
  
  # Database Connection (if using external database)
  DATABASE_URL: "cGxhY2Vob2xkZXItZGF0YWJhc2UtdXJs"                       # placeholder-database-url
  
  # JWT Secret for authentication
  JWT_SECRET: "cGxhY2Vob2xkZXItand0LXNlY3JldC1rZXk="                      # placeholder-jwt-secret-key
  
  # Session Secret
  SESSION_SECRET: "cGxhY2Vob2xkZXItc2Vzc2lvbi1zZWNyZXQ="                 # placeholder-session-secret
  
  # Encryption Key for sensitive data
  ENCRYPTION_KEY: "cGxhY2Vob2xkZXItZW5jcnlwdGlvbi1rZXk="                 # placeholder-encryption-key
  
  # Webhook Secrets (for external integrations)
  WEBHOOK_SECRET: "cGxhY2Vob2xkZXItd2ViaG9vay1zZWNyZXQ="                 # placeholder-webhook-secret
  
  # External Service API Keys
  NOTIFICATION_API_KEY: "cGxhY2Vob2xkZXItbm90aWZpY2F0aW9uLWtleQ=="       # placeholder-notification-key
  ANALYTICS_API_KEY: "cGxhY2Vob2xkZXItYW5hbHl0aWNzLWtleQ=="             # placeholder-analytics-key